from PyQt4 import QtCore, QtGui
import sys

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
	def __init__(self):
		QtGui.QWidget.__init__(self)
		self.setupUi(self)
	def setupUi(self, Form):
		Form.setObjectName(_fromUtf8("Fshare"))
		Form.resize(651, 343)
		self.horizontalLayout = QtGui.QHBoxLayout(Form)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.horizontalLayoutPorts = QtGui.QHBoxLayout()
		self.horizontalLayoutPorts.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
		self.horizontalLayoutPorts.setObjectName(_fromUtf8("horizontalLayoutPorts"))
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutPorts.addItem(spacerItem)
		self.label = QtGui.QLabel(Form)
		self.label.setMaximumSize(QtCore.QSize(100, 25))
		self.label.setObjectName(_fromUtf8("label"))
		self.horizontalLayoutPorts.addWidget(self.label)
		self.textEdit_2 = QtGui.QTextEdit(Form)
		self.textEdit_2.setMaximumSize(QtCore.QSize(100, 25))
		self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
		self.horizontalLayoutPorts.addWidget(self.textEdit_2)
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutPorts.addItem(spacerItem1)
		self.gridLayout.addLayout(self.horizontalLayoutPorts, 7, 0, 1, 1)
		spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
		self.layoutSubmit = QtGui.QHBoxLayout()
		self.layoutSubmit.setObjectName(_fromUtf8("layoutSubmit"))
		spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem10, 4, 0, 1, 1)
		self.btnShare = QtGui.QPushButton(Form)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.btnShare.sizePolicy().hasHeightForWidth())
		self.btnShare.setSizePolicy(sizePolicy)
		self.btnShare.setMaximumSize(QtCore.QSize(200, 100))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Monospace"))
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.btnShare.setFont(font)
		self.btnShare.setObjectName(_fromUtf8("btnShare"))
		self.layoutSubmit.addWidget(self.btnShare)
		self.gridLayout.addLayout(self.layoutSubmit, 15, 0, 1, 1)
		self.labelTitle = QtGui.QLabel(Form)
		self.labelTitle.setEnabled(True)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
		self.labelTitle.setSizePolicy(sizePolicy)
		self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 120))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Monospace"))
		font.setPointSize(24)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.labelTitle.setFont(font)
		self.labelTitle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelTitle.setObjectName(_fromUtf8("labelTitle"))
		self.gridLayout.addWidget(self.labelTitle, 0, 0, 1, 1)
		self.horizontalLayoutSelect = QtGui.QHBoxLayout()
		self.horizontalLayoutSelect.setObjectName(_fromUtf8("horizontalLayoutSelect"))
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutSelect.addItem(spacerItem3)
		self.labelShareChooser = QtGui.QLabel(Form)
		self.labelShareChooser.setObjectName(_fromUtf8("labelShareChooser"))
		self.horizontalLayoutSelect.addWidget(self.labelShareChooser)
		self.btnRadioHttp = QtGui.QRadioButton(Form)
		self.btnRadioHttp.setObjectName(_fromUtf8("btnRadioHttp"))
		self.horizontalLayoutSelect.addWidget(self.btnRadioHttp)
		self.btnRadioFtp = QtGui.QRadioButton(Form)
		self.btnRadioFtp.setObjectName(_fromUtf8("btnRadioFtp"))
		self.horizontalLayoutSelect.addWidget(self.btnRadioFtp)
		spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutSelect.addItem(spacerItem4)
		self.gridLayout.addLayout(self.horizontalLayoutSelect, 10, 0, 1, 1)
		spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem5, 8, 0, 1, 1)
		self.horizontalLayoutFolderShare = QtGui.QHBoxLayout()
		self.horizontalLayoutFolderShare.setSizeConstraint(QtGui.QLayout.SetFixedSize)
		self.horizontalLayoutFolderShare.setSpacing(6)
		self.horizontalLayoutFolderShare.setObjectName(_fromUtf8("horizontalLayoutFolderShare"))
		self.label_2 = QtGui.QLabel(Form)
		self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.horizontalLayoutFolderShare.addWidget(self.label_2)
		self.textEdit = QtGui.QTextEdit(Form)
		self.textEdit.setMaximumSize(QtCore.QSize(16777215, 25))
		self.textEdit.setObjectName(_fromUtf8("textEdit"))
		self.horizontalLayoutFolderShare.addWidget(self.textEdit)
		self.toolButton = QtGui.QToolButton(Form)
		self.toolButton.setMaximumSize(QtCore.QSize(16777215, 25))
		self.toolButton.setObjectName(_fromUtf8("toolButton"))
		self.horizontalLayoutFolderShare.addWidget(self.toolButton)
		self.gridLayout.addLayout(self.horizontalLayoutFolderShare, 3, 0, 1, 1)
		spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem6, 4, 0, 1, 1)
		spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem7, 16, 0, 1, 1)
		self.verticalLayoutLogs = QtGui.QVBoxLayout()
		self.verticalLayoutLogs.setContentsMargins(10, -1, 10, -1)
		self.verticalLayoutLogs.setObjectName(_fromUtf8("verticalLayoutLogs"))
		self.textEditLogs = QtGui.QTextEdit(Form)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textEditLogs.sizePolicy().hasHeightForWidth())
		self.textEditLogs.setSizePolicy(sizePolicy)
		self.textEditLogs.setMaximumSize(QtCore.QSize(16777215, 200))
		self.textEditLogs.setObjectName(_fromUtf8("textEditLogs"))
		self.verticalLayoutLogs.addWidget(self.textEditLogs)
		self.gridLayout.addLayout(self.verticalLayoutLogs, 14, 0, 1, 1)
		spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.gridLayout.addItem(spacerItem8, 2, 0, 1, 1)
		self.horizontalLayout.addLayout(self.gridLayout)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(_translate("Form", "Fshare", None))
		self.label.setText(_translate("Form", "Port : ", None))
		self.btnShare.setText(_translate("Form", "Start Sharing", None))
		self.labelTitle.setText(_translate("Form", "F Share V1.1", None))
		self.labelShareChooser.setText(_translate("Form", "Share over :", None))
		self.btnRadioHttp.setText(_translate("Form", "Http", None))
		self.btnRadioFtp.setText(_translate("Form", "FTP", None))
		self.label_2.setText(_translate("Form", "Folder To Share : ", None))
		self.toolButton.setText(_translate("Form", "...", None))







if __name__ == '__main__':
	app = QtGui.QApplication(sys.argv)
	ex = Ui_Form	()
	ex.show()
	sys.exit(app.exec_())


